apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.component: ert-webhook
  app: ert-webhook
namePrefix: ert-webhook-
resources:
  - deployment.yaml
  - service.yaml
  - mutating-webhook-configuration.yaml
